[2023-06-29 10:58:38,969] root - INFO - 'data' FUNCTION STARTED
[2023-06-29 10:58:38,969] root - INFO - 'feature_engineering' FUNCTION STARTED
[2023-06-29 10:58:38,969] root - INFO - 'freight_cost_transform' FUNCTION STARTED
[2023-06-29 10:58:38,969] root - INFO - 'remove_outliers' FUNCTION STARTED
[2023-06-29 10:58:38,969] root - INFO - 'data_' FUNCTION STARTED
[2023-06-29 10:58:38,969] root - INFO - Reading all params from config_path
[2023-06-29 10:58:38,980] root - INFO - parameters readed from config_path successfully!!!
[2023-06-29 10:58:39,037] root - INFO - Data loaded successfully
[2023-06-29 10:58:39,052] root - INFO - removed outliers function compiled successfully
[2023-06-29 10:58:39,062] root - INFO - freight_cost_transform function compiled successfully
[2023-06-29 10:58:39,075] root - INFO - Exception occurred while compiling the codelocal variable 'lb' referenced before assignment
[2023-06-29 10:58:39,075] root - INFO - Failed to execute the code please check your code and run
[2023-06-29 10:58:39,076] root - INFO - Exception occurred while compiling the codeError occurred python script name [D:\Projects\Consignment\src\stage4_feature_engineering.py] line number [108] error message [local variable 'lb' referenced before assignment].
[2023-06-29 10:58:39,076] root - INFO - Failed to execute the code please check your code and run
